name: 'Until Blog Widget'
description: 'Display your latest Until blog posts in your GitHub README'
author: "namgyu-youn <yynk2012@gmail.com>"

inputs:
  username:
    description: 'Your Until blog username'
    required: true
  max_posts:
    description: 'Maximum number of posts to display'
    required: false
    default: '4'
  title:
    description: 'Widget title'
    required: false
    default: '📝 Until 블로그 최신 글'
  theme:
    description: 'Widget theme (dark/light)'
    required: false
    default: 'dark'
  filename:
    description: 'Output filename'
    required: false
    default: 'blog-widget.svg'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run action
      run: node dist/index.js
      shell: bash
      env:
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_MAX_POSTS: ${{ inputs.max_posts }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_THEME: ${{ inputs.theme }}
        INPUT_FILENAME: ${{ inputs.filename }}